-- 코드를 입력하세요
WITH MISSING_ANIMAL AS (SELECT O.ANIMAL_ID, O.NAME, I.ANIMAL_ID AS MISSING FROM ANIMAL_OUTS O, ANIMAL_INS I WHERE O.ANIMAL_ID = I.ANIMAL_ID(+))
SELECT ANIMAL_ID, NAME FROM MISSING_ANIMAL WHERE MISSING IS NULL ORDER BY ANIMAL_ID ASC;