-- 코드를 입력하세요
WITH HAVYS AS (SELECT HOST_ID FROM (SELECT HOST_ID, COUNT(HOST_ID) AS C FROM PLACES GROUP BY HOST_ID) WHERE C > 1)
SELECT P.* FROM PLACES P, HAVYS H WHERE P.HOST_ID = H.HOST_ID ORDER BY P.ID;