-- 코드를 입력하세요
WITH RESULT AS (SELECT I.ANIMAL_ID, I.NAME, I.DATETIME AS IDATE, O.DATETIME AS ODATE FROM ANIMAL_INS I, ANIMAL_OUTS O WHERE I.ANIMAL_ID = O.ANIMAL_ID)
SELECT ANIMAL_ID, NAME FROM RESULT WHERE IDATE > ODATE ORDER BY IDATE ASC;